server:
  port: 7070

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: wall, stat
      url: jdbc:mysql://8.141.166.181:3306/52Hz?serverTimezone=UTC&characterEncoding=UTF-8 # Christopher's
      username: twt_vote
      password: TWT_vote1895
      initial-size: 5
      min-idle: 1
      max-active: 10
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: utf-8
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/,/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  type-aliases-package: com.example._52hz.entity
  configuration:
    map-underscore-to-camel-case: false
